[server]
headless = true
maxUploadSize = 200

[theme]
primaryColor = "#E61E3D"
backgroundColor = "#F9FAFB"
secondaryBackgroundColor = "#111827"
textColor = "#1F2937"
font = "sans serif"

[browser]
gatherUsageStats = false
